config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show] do
    resources :items, only: [:create, :destroy]
  end
  
  get 'welcome/index'
  get 'welcome/about'
  root to: 'welcome#index'

  

end

app/models/item.rb
class Item < ActiveRecord::Base

  default_scope { order('updated_at DESC')}

  belongs_to :user

  def days_left
    7 - (DateTime.now.to_date - created_at.to_date).to_i
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u| 
      u.permit(:password, :password_confirmation, :current_password) 
    }
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @item = @user.items.build( item_params )

    if @item.save
      redirect_to user_path(@user), notice: 'Your item has been saved.'
    else
      flash[:error] = 'There was an error saving your item'
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @item = @user.items.find(params[:id])

    if @item.destroy
      flash[:notice] = "Comment was removed."
    else
      flash[:error] = "Comment couldn't be deleted. Please try again."
    end
    
    respond_to do |format|
      format.html { redirect_to user_items_path(@user) }
      format.js   
    end
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    user = User.new
  end
  
  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Invalid user information"
      redirect_to edit_user_registration_path
    end
  end

  def show
    @user = User.find(params[:id])
    @items = @user.items
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [@user, Item.new] do |f| %>
  <h3> Add an item to your to-do list </h3>
    <div class = "field">
      <%= f.label :name %> <br />
      <%= f.text_field :name %>
    </div>
    <div class ="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/items/_item.html.erb
<div id=<%="item-#{item.id}"%> class="item list-group-item">
  <button type="button" class="btn btn-default btn-lg display-inline-right">
    <span class="glyphicon glyphicon-ok completed-icon" aria-hidden="true"></span>
    <%= link_to 'Item Completed', user_item_path(@user, item), method: :delete, remote: true %>
  </button>
  <h4 class='list-group-item-heading'><%= item.name %></h4> 
  <p class='list-group-item-text'><%= item.days_left %> days left to complete</p>
</div>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('#item-' +<%= @item.id %>).hide("slow");
  $('.js-items-count').html("<%= pluralize(@item.user.items.count, 'item') %>");
<% else %>
  $('#item-' +<%= @item.id %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Bloccitoff", root_path %></li>

     <div class="pull-right user-info">
          <% if current_user %>
            Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %> or
            <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </div>
      </ul>

<%= yield %>

</body>
</html>

app/views/user/show.html.erb
<div class = "row">
  <div class="col-md-8">
    <div class="media-body">
         <h2 class="media-heading"><%= @user.name %></h2>
         </div>
        </div>
      </div>

app/views/users/show.html.erb
<div class = "row">
  <div class="col-md-8">
    <div class="media-body">
         <h2 class="media-heading"><%= @user.name %></h2>
         <h2> <%= @user.email %> </h2>
         <p> <%= render 'items/form' %> </p>
         <p> <%= render @items %> </p>
         <div class='js-items-count'><%= pluralize(@user.items.count, 'item') %></div>
        </div>
      </div>
    </div>

app/views/welcome/about.html.erb
<h1>Bloccitoff</h1>
<p>Self-destructing to-do list app created by Allison Goldfarb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Bloccitoff</h1>
  <p>Bloccitoff is a self-destructing to-do list app</p>
  <p>
    <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today! 
    </p>
    </div>